import Link from "next/link";
import { ArrowLeft, BadgeCheck, BriefcaseMedical, GraduationCap, ShieldCheck, Stethoscope, Wrench } from "lucide-react";
import { notFound } from "next/navigation";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getProfessionalConfiguration } from "@/lib/catalog/queries";
import { addProfessionalQualification, addProfessionalRegistration, addSpecialtyRegistration, reviewSpecialtyRegistration, toggleProfessionalRecord, toggleProfessionalService, toggleProfessionalSpecialty, updateProfessional } from "../../actions";

export default async function ProfessionalPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ status?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const data = await getProfessionalConfiguration(id);
  if (!data.professional && !data.error) notFound();
  const professional = data.professional;
  const canManage = data.role === "admin";
  const updateAction = updateProfessional.bind(null, id);
  const registrationAction = addProfessionalRegistration.bind(null, id);
  const specialtyAction = toggleProfessionalSpecialty.bind(null, id);
  const qualificationAction = addProfessionalQualification.bind(null, id);
  const serviceAction = toggleProfessionalService.bind(null, id);
  const specialtyRegistrationAction = addSpecialtyRegistration.bind(null, id);
  const registeredProfessionIds = new Set(data.registrations.filter((item) => item.active).map((item) => item.profession_id));
  const visibleSpecialties = data.specialties.filter((item) => item.profession_id && registeredProfessionIds.has(item.profession_id));
  const assignedSpecialties = visibleSpecialties.filter((item) => data.selectedSpecialtyIds.includes(item.id));
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Ficha profissional</p><h1 className="text-3xl font-semibold tracking-tight">{professional?.name ?? "Profissional"}</h1><p className="mt-1 text-muted-foreground">Cadastro profissional separado da conta de acesso ao sistema.</p></div><Button asChild variant="outline"><Link href="/dashboard/cadastros"><ArrowLeft />Voltar</Link></Button></div>
    {query.status === "saved" && <Alert><AlertTitle>Ficha atualizada</AlertTitle><AlertDescription>A alteração foi salva e auditada.</AlertDescription></Alert>}
    {query.status === "invalid" && <Alert variant="destructive"><AlertTitle>Dados inválidos</AlertTitle><AlertDescription>Conselho, UF e número devem ser preenchidos juntos quando aplicáveis.</AlertDescription></Alert>}
    {query.status === "error" && <Alert variant="destructive"><AlertTitle>Não foi possível salvar</AlertTitle><AlertDescription>Verifique duplicidade, validade e regras de integridade.</AlertDescription></Alert>}
    {data.error && <Alert variant="destructive"><AlertTitle>Ficha incompleta</AlertTitle><AlertDescription>{data.error}</AlertDescription></Alert>}
    <div className="grid gap-5 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Dados básicos</CardTitle><CardDescription>Identificação e contatos profissionais.</CardDescription></CardHeader><CardContent><form action={updateAction} className="grid gap-4 sm:grid-cols-2"><Field name="fullName" label="Nome completo" value={professional?.name} /><Field name="displayName" label="Nome de exibição" value={professional?.display_name} required={false} /><Field name="email" label="E-mail profissional" value={professional?.email} type="email" required={false} /><Field name="phone" label="Telefone profissional" value={professional?.phone} required={false} /><div className="sm:col-span-2"><Button disabled={!canManage}>Salvar dados básicos</Button></div></form></CardContent></Card>
      <Card><CardHeader><div className="flex items-center gap-2"><BadgeCheck className="size-5 text-primary" /><CardTitle>Profissão e registro</CardTitle></div><CardDescription>Conselho é opcional; quando utilizado, sigla, número e UF são obrigatórios em conjunto.</CardDescription></CardHeader><CardContent className="space-y-5"><form action={registrationAction} className="grid gap-4 sm:grid-cols-2"><SelectField name="professionId" label="Profissão" items={data.professions} /><SelectField name="councilId" label="Conselho (se aplicável)" items={data.councils.map((item) => ({ id: item.id, name: `${item.acronym} — ${item.name}` }))} required={false} /><div className="space-y-2"><Label htmlFor="stateCode">UF do conselho</Label><select id="stateCode" name="stateCode" className="h-9 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">Não aplicável</option>{data.states.map((item) => <option key={item.code} value={item.code}>{item.name} — {item.code}</option>)}</select></div><Field name="registrationNumber" label="Número do registro" required={false} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="primary" />Registro principal</label><div><Button disabled={!canManage || data.professions.length === 0}>Adicionar registro</Button></div></form><div className="rounded-lg border"><Table><TableHeader><TableRow><TableHead>Profissão</TableHead><TableHead>Registro</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{data.registrations.length === 0 ? <EmptyRow columns={3} /> : data.registrations.map((item) => <TableRow key={item.id}><TableCell>{item.professions?.name}{item.primary_registration && <Badge className="ml-2" variant="secondary">Principal</Badge>}</TableCell><TableCell>{item.professional_councils ? `${item.professional_councils.acronym} ${item.registration_number}/${item.state_code}` : "Conselho não aplicável"}</TableCell><TableCell><ToggleRecord kind="registration" professionalId={id} id={item.id} active={item.active} disabled={!canManage} /></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center gap-2"><Stethoscope className="size-5 text-primary" /><CardTitle>Especialidades oficiais</CardTitle></div><CardDescription>O catálogo é filtrado pelas profissões ativas do profissional. Áreas de atuação exigem suas especialidades pré-requisito.</CardDescription></CardHeader><CardContent className="space-y-3">{visibleSpecialties.length === 0 ? <EmptyState text="Adicione primeiro um registro profissional ativo para exibir o catálogo correspondente." /> : visibleSpecialties.map((item) => { const enabled = data.selectedSpecialtyIds.includes(item.id); const prerequisiteIds = data.specialtyPrerequisites.filter((link) => link.specialty_id === item.id).map((link) => link.prerequisite_specialty_id); const missingPrerequisite = prerequisiteIds.some((requiredId) => !data.selectedSpecialtyIds.includes(requiredId)); return <form action={specialtyAction} key={item.id} className="flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><input type="hidden" name="specialtyId" value={item.id} /><input type="hidden" name="enabled" value={String(enabled)} /><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{item.name}</span><Badge variant={item.classification === "specialty" ? "secondary" : "outline"}>{item.classification === "specialty" ? "Especialidade" : "Área de atuação"}</Badge>{item.official_code && <Badge variant="outline">Código {item.official_code}</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{item.specialty_catalog_releases?.regulatory_authorities?.acronym} · {item.specialty_catalog_releases?.version_label}{missingPrerequisite && " · associe primeiro os pré-requisitos"}</p></div><Button size="sm" variant={enabled ? "secondary" : "outline"} disabled={!canManage || (!enabled && missingPrerequisite)}>{enabled ? "Associada" : "Associar"}</Button></form>; })}</CardContent></Card>
      <Card><CardHeader><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-primary" /><CardTitle>Registro de especialista (RQE)</CardTitle></div><CardDescription>O RQE é independente da associação da especialidade. Novos registros começam pendentes e só são confirmados com uma fonte oficial.</CardDescription></CardHeader><CardContent className="space-y-5"><form action={specialtyRegistrationAction} className="grid gap-4 sm:grid-cols-2"><SelectField name="specialtyId" label="Especialidade ou área associada" items={assignedSpecialties} /><SelectField name="councilId" label="Conselho emissor" items={data.councils.map((item) => ({ id: item.id, name: `${item.acronym} — ${item.name}` }))} /><div className="space-y-2"><Label htmlFor="rqeStateCode">UF do conselho</Label><select id="rqeStateCode" name="stateCode" required className="h-9 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">Selecione</option>{data.states.map((item) => <option key={item.code} value={item.code}>{item.name} — {item.code}</option>)}</select></div><Field name="rqeNumber" label="Número do RQE" /><Field name="validFrom" label="Início da vigência" type="date" required={false} /><Field name="validUntil" label="Fim da vigência" type="date" required={false} /><div className="sm:col-span-2"><Button disabled={!canManage || assignedSpecialties.length === 0}>Registrar como pendente</Button></div></form><div className="space-y-3">{data.specialtyRegistrations.length === 0 ? <EmptyState text="Nenhum RQE registrado." /> : data.specialtyRegistrations.map((item) => <div key={item.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{item.specialties?.name}</p><p className="text-xs text-muted-foreground">{item.professional_councils?.acronym} {item.rqe_number}/{item.state_code}</p></div><VerificationBadge status={item.verification_status} /></div><form action={reviewSpecialtyRegistration.bind(null, id, "verified")} className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><input type="hidden" name="id" value={item.id} /><div className="space-y-1"><Label htmlFor={`source-${item.id}`}>Fonte oficial da conferência</Label><Input id={`source-${item.id}`} name="sourceUrl" type="url" placeholder="https://..." defaultValue={item.verification_source_url ?? ""} /></div><Button className="self-end" disabled={!canManage || item.verification_status === "verified"}>Confirmar</Button><Button className="self-end" variant="outline" formAction={reviewSpecialtyRegistration.bind(null, id, "inconclusive")} disabled={!canManage}>Inconclusivo</Button></form></div>)}</div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center gap-2"><GraduationCap className="size-5 text-primary" /><CardTitle>Qualificações</CardTitle></div><CardDescription>Cursos e certificações adicionais, sem presumir habilitação legal.</CardDescription></CardHeader><CardContent className="space-y-5"><form action={qualificationAction} className="grid gap-4 sm:grid-cols-2"><SelectField name="qualificationId" label="Qualificação" items={data.qualifications} /><Field name="certificateNumber" label="Número do certificado" required={false} /><Field name="issuedOn" label="Data de emissão" type="date" required={false} /><Field name="expiresOn" label="Validade" type="date" required={false} /><div className="sm:col-span-2"><Button disabled={!canManage || data.qualifications.length === 0}>Adicionar qualificação</Button></div></form><div className="rounded-lg border"><Table><TableHeader><TableRow><TableHead>Qualificação</TableHead><TableHead>Certificado</TableHead><TableHead>Situação</TableHead></TableRow></TableHeader><TableBody>{data.assignedQualifications.length === 0 ? <EmptyRow columns={3} /> : data.assignedQualifications.map((item) => <TableRow key={item.id}><TableCell>{item.qualifications?.name}</TableCell><TableCell>{item.certificate_number || "Não informado"}{item.expires_on && ` · vence em ${item.expires_on}`}</TableCell><TableCell><ToggleRecord kind="qualification" professionalId={id} id={item.id} active disabled={!canManage} /></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
      <Card className="xl:col-span-2"><CardHeader><div className="flex items-center gap-2"><BriefcaseMedical className="size-5 text-primary" /><CardTitle>Serviços habilitados</CardTitle></div><CardDescription>A habilitação é explícita e pode definir duração diferente do padrão.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{data.services.length === 0 ? <EmptyState text="Nenhum serviço ativo disponível." /> : data.services.map((service) => { const assignment = data.assignedServices.find((item) => item.service_id === service.id); const enabled = Boolean(assignment); return <form action={serviceAction} key={service.id} className="grid gap-3 rounded-lg border p-4 sm:grid-cols-[1fr_9rem_auto]"><input type="hidden" name="serviceId" value={service.id} /><input type="hidden" name="enabled" value={String(enabled)} /><div><p className="font-medium">{service.name}</p><p className="text-xs text-muted-foreground">{service.service_categories?.name} · padrão {service.default_duration_minutes} min</p></div><div className="space-y-1"><Label htmlFor={`duration-${service.id}`}>Duração própria</Label><Input id={`duration-${service.id}`} name="durationOverride" type="number" min="5" max="1440" defaultValue={assignment?.duration_override_minutes ?? ""} placeholder="Padrão" /></div><div className="flex items-end"><Button size="sm" variant={enabled ? "secondary" : "outline"} disabled={!canManage}>{enabled ? "Habilitado" : "Habilitar"}</Button></div></form>; })}</CardContent></Card>
      <Card className="xl:col-span-2"><CardHeader><div className="flex items-center gap-2"><Wrench className="size-5 text-primary" /><CardTitle>Conta de acesso</CardTitle></div><CardDescription>A criação de usuário e perfil de acesso permanece separada desta ficha. Nenhuma conta é criada automaticamente.</CardDescription></CardHeader></Card>
    </div>
  </div>;
}

function Field({ name, label, value, type = "text", required = true }: { name: string; label: string; value?: string | null; type?: string; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><Input id={name} name={name} type={type} defaultValue={value ?? ""} required={required} /></div>; }
function SelectField({ name, label, items, required = true }: { name: string; label: string; items: { id: string; name: string }[]; required?: boolean }) { return <div className="space-y-2"><Label htmlFor={name}>{label}</Label><select id={name} name={name} required={required} className="h-9 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">{required ? "Selecione" : "Não aplicável"}</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div>; }
function EmptyState({ text }: { text: string }) { return <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</p>; }
function EmptyRow({ columns }: { columns: number }) { return <TableRow><TableCell colSpan={columns} className="h-20 text-center text-muted-foreground">Nenhum vínculo cadastrado.</TableCell></TableRow>; }
function VerificationBadge({ status }: { status: "pending" | "verified" | "rejected" | "inconclusive" }) { const labels = { pending: "Pendente", verified: "Verificado", rejected: "Rejeitado", inconclusive: "Inconclusivo" }; return <Badge variant={status === "verified" ? "secondary" : "outline"}>{labels[status]}</Badge>; }
function ToggleRecord({ kind, professionalId, id, active, disabled }: { kind: "registration" | "qualification"; professionalId: string; id: string; active: boolean; disabled: boolean }) { const action = toggleProfessionalRecord.bind(null, kind, professionalId); return <form action={action}><input type="hidden" name="id" value={id} /><input type="hidden" name="active" value={String(active)} /><Button size="sm" variant="ghost" disabled={disabled}><Badge variant={active ? "secondary" : "outline"}>{active ? "Ativo" : "Inativo"}</Badge></Button></form>; }
