import Link from "next/link";
import { ArrowLeft, Banknote, BriefcaseMedical, Building2, ClipboardCheck, PackageOpen, UsersRound } from "lucide-react";
import { notFound } from "next/navigation";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { getServiceConfiguration, type CatalogItem } from "@/lib/catalog/queries";
import { addServicePrice, toggleServiceAssociation } from "../../actions";

export default async function ServiceConfigurationPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ status?: string }> }) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  const data = await getServiceConfiguration(id);
  if (!data.service && !data.error) notFound();
  const canManage = data.roles.includes("admin");
  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Configuração do serviço</p><h1 className="text-3xl font-semibold tracking-tight">{data.service?.name ?? "Serviço"}</h1><p className="mt-1 text-muted-foreground">{data.service?.service_categories?.name} · {data.service?.default_duration_minutes} minutos · capacidade {data.service?.default_capacity}</p></div><Button asChild variant="outline"><Link href="/dashboard/cadastros"><ArrowLeft />Voltar</Link></Button></div>
    {query.status === "saved" && <Alert><AlertTitle>Configuração atualizada</AlertTitle><AlertDescription>A associação foi salva e auditada.</AlertDescription></Alert>}
    {query.status === "error" && <Alert variant="destructive"><AlertTitle>Não foi possível salvar</AlertTitle><AlertDescription>Verifique as regras de integridade e tente novamente.</AlertDescription></Alert>}
    {data.error && <Alert variant="destructive"><AlertTitle>Configuração incompleta</AlertTitle><AlertDescription>{data.error}</AlertDescription></Alert>}
    <div className="grid gap-5 xl:grid-cols-2">
      <AssociationCard title="Capacidades assistenciais" description="Comportamentos clínicos suportados pelo serviço." icon={ClipboardCheck} items={data.capabilities} selectedIds={data.selectedCapabilityIds} serviceId={id} kind="capability" canManage={canManage} />
      <AssociationCard title="Modalidade de atendimento" description="Atendimento individual ou coletivo." icon={UsersRound} items={data.deliveryModes} selectedIds={data.selectedDeliveryModeIds} serviceId={id} kind="delivery" canManage={canManage} />
      <AssociationCard title="Formas de cobrança" description="Como este serviço pode ser comercializado ou faturado." icon={Banknote} items={data.billingModes} selectedIds={data.selectedBillingModeIds} serviceId={id} kind="billing" canManage={canManage} />
      <AssociationCard title="Salas permitidas" description="Espaços aptos a receber o serviço." icon={Building2} items={data.rooms} selectedIds={data.selectedRoomIds} serviceId={id} kind="room" canManage={canManage} detail={(item) => `capacidade ${item.capacity}`} />
      <AssociationCard title="Recursos necessários" description="Equipamentos disponíveis para o serviço." icon={PackageOpen} items={data.resources} selectedIds={data.selectedResourceIds} serviceId={id} kind="resource" canManage={canManage} detail={(item) => `quantidade ${item.quantity}`} />
      <AssociationCard title="Profissionais habilitados" description="Permanece vazio até existirem dados profissionais reais." icon={BriefcaseMedical} items={data.professionals} selectedIds={data.selectedProfessionalIds} serviceId={id} kind="professional" canManage={canManage} />
      <Card className="xl:col-span-2"><CardHeader><CardTitle>Histórico de preços</CardTitle><CardDescription>Novo preço cria uma vigência; valores anteriores não são sobrescritos.</CardDescription></CardHeader><CardContent className="space-y-5"><form action={addServicePrice} className="grid gap-3 sm:grid-cols-[1fr_1fr_1fr_auto]"><input type="hidden" name="serviceId" value={id} /><div className="space-y-2"><Label htmlFor="billingModeId">Forma de cobrança</Label><select id="billingModeId" name="billingModeId" className="h-9 w-full rounded-md border bg-transparent px-3 text-sm"><option value="">Preço geral</option>{data.billingModes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="space-y-2"><Label htmlFor="amount">Valor (R$)</Label><Input id="amount" name="amount" type="number" min="0" step="0.01" required /></div><div className="space-y-2"><Label htmlFor="validFrom">Início da vigência</Label><Input id="validFrom" name="validFrom" type="date" required /></div><div className="flex items-end"><Button disabled={!canManage}>Adicionar preço</Button></div></form><div className="rounded-lg border"><Table><TableHeader><TableRow><TableHead>Forma</TableHead><TableHead>Valor</TableHead><TableHead>Vigência</TableHead></TableRow></TableHeader><TableBody>{data.prices.length === 0 ? <TableRow><TableCell colSpan={3} className="h-24 text-center text-muted-foreground">Nenhum preço cadastrado.</TableCell></TableRow> : data.prices.map((price) => <TableRow key={price.id}><TableCell>{price.billing_modes?.name ?? "Geral"}</TableCell><TableCell>{new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(price.amount)}</TableCell><TableCell>{price.valid_from}{price.valid_until ? ` até ${price.valid_until}` : " em vigor"}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
    </div>
  </div>;
}

function AssociationCard<T extends CatalogItem>({ title, description, icon: Icon, items, selectedIds, serviceId, kind, canManage, detail }: { title: string; description: string; icon: typeof ClipboardCheck; items: T[]; selectedIds: string[]; serviceId: string; kind: "capability" | "delivery" | "billing" | "room" | "resource" | "professional"; canManage: boolean; detail?: (item: T) => string }) { const action = toggleServiceAssociation.bind(null, kind); return <Card><CardHeader><div className="flex items-center gap-2"><Icon className="size-5 text-primary" /><CardTitle>{title}</CardTitle></div><CardDescription>{description}</CardDescription></CardHeader><CardContent><div className="space-y-2">{items.length === 0 ? <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">Nenhum item disponível.</p> : items.map((item) => { const enabled = selectedIds.includes(item.id); return <form action={action} key={item.id} className="flex items-center justify-between gap-3 rounded-lg border p-3"><input type="hidden" name="serviceId" value={serviceId} /><input type="hidden" name="targetId" value={item.id} /><input type="hidden" name="enabled" value={String(enabled)} /><div><p className="font-medium">{item.name}</p>{detail && <p className="text-xs text-muted-foreground">{detail(item)}</p>}</div><Button type="submit" size="sm" variant={enabled ? "secondary" : "outline"} disabled={!canManage}><Badge variant={enabled ? "secondary" : "outline"}>{enabled ? "Associado" : "Associar"}</Badge></Button></form>; })}</div></CardContent></Card>; }
